=== Overview of available model objects
		
During startup the Eclipse framework parses the available information about the application model (Application.e4xmi, persisted user changes and model contributions) and stores this information in Java objects.
These objects are called _model objects_ and at runtime they represent the attributes from the model elements.

 The following table lists the types of the important model objects.

.Eclipse model elements
|===
|Model element |Description

|MApplication
|Describes the application object. All other model elements are contained in this object.

|MAddon
|A self-contained component typically without user interface.
It can register for events in the application life cycle and handle these events.

|MWindow
|Represents a window in your application.

|MTrimmedWindow
|Similar to MWindow but it allows containing toolbars for the windows (via the TrimBars model elements).

|MPerspective
|Represents a different layout of parts to be shown inside the window. Should be contained in a MPerspectiveStack.

|MPart
|Represents the model element part, e.g., a view or an editor.

|MDirtyable
|Property of MPart which can be injected. If set to true, this property informs the Eclipse platform that this Part contains unsaved data (is dirty).
In a handler you can query this property to provide a save possibility.

|MPartDescriptor
|MPartDescriptor is a template for new parts.
A new part based on this part descriptor can be created and shown via the Eclipse framework.

|Snippets
|Snippets can be used to pre-configure model parts which you want to create via your program.
You can use the Eclipse framework to clone such a snippet and use the result object to attach it to the application model at runtime.

