== Menu and toolbar application objects

=== Adding menu and toolbar entries

You can add menus and toolbars to your RCP application via the application model.
These entries can be positioned at various places.
You can, for example, add a menu to a window or a part.
These elements define, directly or indirectly, a link to a class.
An instance of this class is created by the framework and responsible for the behavior if the menu or toolbar entry is selected.
Such a class is called _handler class_.

=== The usage of commands and handlers

The Eclipse application model allows you to specify _commands_ and _handlers_.

The usage of the commands and handlers model element is optional.
You can use the _Direct MenuItem_ or a _Direct ToolItem_ model elements.
These entries define a reference to a class (handler class). An instance of this handler class is created by the framework and its annotated methods are called by the framework if necessary.
Menus and toolbars support separators.

A command is a declarative description of an abstract action which can be performed, for example, _save_, _edit_ or _copy_.

A command is independent from its implementation details. The Eclipse framework does
not provide standard commands, e.g., you have to create all required commands in your application model.

The behavior of a command is defined via a handler.
A handler model element points to a class (handler class) via the `contributionURI` property of the handler.
This attribute is displayed as _Class URI_ in the model editor.

Commands are used by the _Handled MenuItem_ and _Handled ToolItem_ model elements.

Prefer the usage of commands over the usage of direct (menu or tool) items.
Using commands together with handlers allows you to define different handlers for different scopes (applications or part) and you can define key bindings for the handler's associated commands.

=== Behavior annotations and dependency injection for handler classes
(((Behavior annotations, Handler)))
In a handler class exactly one method must be annotated with the `@Execute` annotation.
In additional, you can also annotate one method with the `@CanExecute` annotation.
If you annotate more than one method with the same annotation, the framework calls only one of them.
The Eclipse runtime uses dependency injection to provide the parameters of the method.
The purpose of these annotations are described in the following table.

.Behavior annotations for handler classes
[cols="1,4",options="header"]
|===
|Annotation |Description

|@Execute
|Marks the method which is responsible for the action of the handler class.
The framework executes this method once the related user interface element, e.g., the menu entry, is selected.

|@CanExecute
|Marks a method to be visited by the Eclipse framework to check if the handler class can be executed.
If a handler class returns `false` in this method, Eclipse disables the corresponding user interface element.
For example, the save button is active if the handler class returns true in the `@CanExecute` method.
The default for this method is true, which means, if the handler class can always be executed, it does not need to implement a `@CanExecute` method.
|===

The following example demonstrates the implementation of a handler class.

[source,java]
----
include::res/command/Example.java[]
----

A handler instance does not have its own Eclipse context ( `IEclipseContext`).
It is executed with the Eclipse context of the active model element which has a Eclipse context.
In most common cases this is the context of the active part.

All required parameters should be injected into the method annotated with `@Execute` , as you want the handler class to retrieve its runtime information during execution.


[WARNING]
====
To ensure that you get the expected values from the active context ALWAYS get the required values injected as parameters into your methods annotated with @Execute or @CanExecute.
====

=== Determining the relevant handler for a command

If a command is selected, the runtime determines the relevant handler for the command. 
The application model allows you to create a handler for the application, a window and a part.

Each command can have only one valid handler for a given scope.
The Eclipse framework selects the handler most specific to the model element.

For example, if you have two handlers for the "Copy" command, one for the window and another one for the part then the runtime selects the handlers closest to model element which is currently selected by the user.

=== Evaluation of @CanExecute

A method annotated with `@CanExecute` is called by the framework, if a change in the Eclipse context happens.
For example, if you select a new part.
If the method returns `false`, the framework disables any menu and tool items that point to that command.

You can request the re-evaluation of the `@CanExecute` methods by sending out an event via the event broker.

[source,java]
----
include::res/canexecutetrigger/triggerevent.java[]
----

=== Mnemonics

The application model allows you to define _mnemonics_.
A mnemonic appears as an underlined letter in the menu when the user presses and holds the kbd:[ALT] key and allows the user to quickly access menu entries by keyboard.

You specify mnemonics by prefixing the letter intended to be the mnemonic with an ampersand (`&`) in the label definition.
For example, if you use the the label _&Save_, the S will be underlined if the kbd:[Alt] key is pressed.

=== Naming schema for command and handler IDs
(((Naming conventions, Command IDs)))
(((Naming conventions, Handler IDs)))
A good convention is to start IDs with the _top level package name_ of your project and to use only lower case letters.

The IDs of commands and handlers should reflect their relationship.
For example, if you implement a command with the `com.example.contacts.commands.show` ID, you should use `com.example.contacts.handler.show` as the ID for the handler.
If you have more than one handler for one command, add another suffix to it, describing its purpose, e.g., `com.example.contacts.handler.show.details`.

In case you implement commonly used functions, e.g., save, copy, you should use the existing platform IDs, as some Eclipse contributions expect these IDs to better integrate with the OS (e.g., on Mac OS, preferences are normally placed under the first menu).
A more complete list of command IDs is available in `org.eclipse.ui.IWorkbenchCommandConstants`.
		

.Default IDs for commonly used commands
|===
|Command |ID

|Save
|org.eclipse.ui.file.save

|Save All
|org.eclipse.ui.file.saveAll

|Undo
|org.eclipse.ui.edit.undo

|Redo
|org.eclipse.ui.edit.redo

|Cut
|org.eclipse.ui.edit.cut

|Copy
|org.eclipse.ui.edit.copy

|Paste
|org.eclipse.ui.edit.paste

|Delete
|org.eclipse.ui.edit.delete

|Import
|org.eclipse.ui.file.import

|Export
|org.eclipse.ui.file.export

|Select All
|org.eclipse.ui.edit.selectAll

|About
|org.eclipse.ui.help.aboutAction

|Preferences
|org.eclipse.ui.window.preferences

|Exit
|org.eclipse.ui.file.exit
|===

