[[exercisetycho_unit]]
== Exercise: Tycho build for test plug-ins

[[exercisetycho_unit_target]]
=== Target of this exercise
		
The following exercise demonstrates how to run unit tests with Tycho. 
It is based on the  <<exercisetychoplugin>> and <<exercisetychofeature>> exercises.
		
The tests of the implementation belong into a separate plug-in or fragment project.
We decide that our software tests should test the API defined by the plug-in, therefore we create a plug-in for the unit tests.

[[exercisetycho_unit_testproject]]

=== Create a new plug-in for the tests
		
Create a new plug-in project called _com.vogella.tycho.unittests_.
		
Define a dependency to `org.junit;bundle-version="4.12.0` and `com.vogella.tycho.plugin1`in its _MANIFEST.MF_ file.
		
		
Create the following pom.xml file for the _com.vogella.tycho.unittests_ project.
		
[source,xml]
----
include::res/tests/pom.xml[]     
----      

[[exercisetycho_unit_unittest]]
=== Create a unit test

Create the following unit test, as an example. 
Of course this test does not test anything real. 
It is only used to demonstrate how Tycho runs the tests.

[source,xml]
----
include::res/tests/ExampleTest.java[]     
----	

[[exercisetycho_unit_master]]		
=== Add new project to the aggregator project
		
Add your new plug-in to the releng pom file.
		
[source,xml]
----
include::res/tests/aggregatorpom.xml[]     
----    
