== More Tycho settings


=== Using root level features

A root level feature is a feature which can be updated or uninstalled independently of the product.
		
To define that a feature is a root level feature, add installMode="root" behind the feature in the product definition file.
You need to use a text editor for this at the moment, the product configuration editor does currently not expose that in its user interface.


	
=== Source Encoding
        
You can set the source code encoding via the `project.build.sourceEncoding` parameter.

[source,xml]
----
include::res/setting/enc.txt[]
----        
        
[WARNING]
====
If you do not set this encoding property the maven build throws warnings similar to the following:
---- ﻿
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
====        
                
For further information see Maven FAQ for encoding warning (http://maven.apache.org/general.html#encoding-warning).


=== Using a repository mirror

You can create p2 repository mirrors, e.g., you can create a mirror of an update site of an Eclipse release. 
For this you can use the mirrorApplication of Eclipse.
		
[source,xml]
----
include::res/mirror/mirror.txt[]
---- 
		
To use your mirror, configure Maven to use it via the _settings.xml_ file in your home folder.

[source,xml]
----
include::res/mirror/usemirror.txt[]
---- 	
		

=== Removing compiler warning messages from the build
		
You can remove compiler warnings from the Maven build by configuring the `tycho-compiler-plugin`. 
This is demonstrated with the following snippet.
		
[source,xml]
----
include::res/compiler/warning.txt[]
----    
        	

=== Using the last Git commit as build qualifier special build settings

You can configure the `tycho-packaging-plugin` to use the last Git commit as build qualifier instead of the build time.
The following pom file shows how to do this. 
This allows building reproducible results if no change happened in the Git repository.
This only works if the project is in a Git repository.
	
[source,xml]
----
include::res/tycho/git_timestamps.xml[]
----
  	

=== Generating and updating POM files for Eclipse components


==== Generating POM files
        
Tycho supports the generation of POM files via its `tycho-pomgenerator-plugin:generate-poms` goal. 
This goals search from the existing directory for Eclipse components which do not yet have a pom files and generates them.
        
You can use the following command to generate the pom files. The `-DgroupId` allows you to specify the group ID for the pom files.

[source, shell]
----
include::res/gen/gen1.txt[]
----       
        
This command generates pom files for all Eclipse components below the current directory and a parent pom in the current directory which includes all Eclipse components as modules.
        
        
For identifying test bundles the generator assumes that those bundles have _.test_ as suffix. ﻿
By using `-DtestSuffix=.mytestBundleSuffix` as additional parameter you can override this default.
        

If you try to execute this generated pom file, the build fail because you have not yet configured your dependencies.
        

If you want to include Eclipse components which are not in the current directory you can point Tycho to these directories via the `-DextraDirs` parameter and define from which directory it should start.
        
[source, shell]
----
include::res/gen/gen2.txt[]
----


=== Update POM files with new version number

You can also update existing pom files with the latest version number via the following command.

[source, shell]
----
include::res/gen/update_pom_version.txt[]
----
        
=== Setting version numbers
        
After releasing an application or several plug-ins, the version number should be increased. 
If you do not use pomless builds, there are two locations where version numbers are defined. 
On the one hand the _pom.xml_ file and on the other hand the _MANIFEST.MF_ file.
        
This can be done easily by using the ﻿Tycho Versions Plugin.

[source, shell]
----
include::res/gen/set_version_no.txt[]
----        
        
Eclipse usually uses semantic versioning for plug-ins, so a version number like {major}.{minor}.{patch} is used.
See http://www.osgi.org/wiki/uploads/Links/SemanticVersioning.pdf[Semantic versioning] for more information.
        
[NOTE]
====                   
The `tycho.mode=maven` property ﻿disables the target platform calculation and dependency ﻿resolution, which is usually done by Tycho. 
This results in better performance, since those features are not necessary for updating the version.
====                
        
More information about versioning with Tycho can be found in the https://eclipse.org/tycho/sitedocs/tycho-release/tycho-versions-plugin/plugin-info.html[Tycho version wiki].



=== Signing plug-ins

If the user installs plug-ins which are not signed, the user received a warning that the plug-in is not signed.
    
The Tycho build system allows to sign plug-ins and executables.
You can purchase a certificate from a certification authority or create your own signature and use this for signing. 
If you use a custom generated certificate the user receives a warning that the certificate is not official.
    
For testing a self-generated certificate is sufficient. 
You can generate such a certificate on the command line with the `keytool` from the Java Development Kit. 
This requires that the corresponding directory is in your current execution path.
    
[source,shell]
----
include::res/signing/create.txt[]
----


To sign the plug-ins add the configuration for the `maven-jarsigner-plugin`

[source,xml]
----
include::res/signing/pom-addon.txt[]
----


=== Building native components

Building native components, for example based on C or C++ code, is typically done via antrunner calling the native build system like make.

See the following commit for an example:

http://git.eclipse.org/c/cdt/org.eclipse.cdt.git/commit/?id=dff6b3bae3ddb27df5433ce7ff3ebb2f4c90de6d

