== Deploying in Eclipse RCP application

=== BIRT deploying to an RCP Application

We can use the Birtviewer also in a local RCP Application, it
isn't more than an browser view which shows a HTML Page generated by
an integrated Webserver.
		
The following assumes that you are already familiar with Eclipse RCP
development. See
http://www.vogella.com/tutorials/RichClientPlatform/article.html[Eclipse RCP Tutorial]
in case you need an introduction.
		
Convert "de.vogella.birt.stocks" to a plug-in project, via
right-click -> Configure -> "Convert to plug-in project".
		
Create an new plug-in project "de.vogella.birt.stocks.rcp".
Select the template "RCP Application with a view".

Add the following plugins as dependendies to
"de.vogella.birt.stocks.rcp".
		
[source,text]
----
include::res/rcp/MANIFEST.MF[]
----
		
Copy your report to "stock_report_rcp.rptdesign" into this new project. Open this
report and change the "open" JavaScript to the following.
		
[source,text]
----
include::res/rcp/fetch.txt[]
----
		
Use this code as View.java.
		
[source,java]
----
include::res/rcp/View.java[]
----
	
