== Handler

=== Command Handler
		
The `org.eclipse.ui.handlers` extension point connects the command to a certain class which is called once the command is executed.
		
The behavior of a command is defined via handlers. 
The handler is the class which is executed once the command is called.
It must implement the `IHandler` interface from the `org.eclipse.core.commands` package.
		
You can extend the `org.eclipse.core.commands.AbstractHandler` class which provides a default implementation for the `IHandler` interface.
		
The `execute()` method is called, if the handler is executed.
		
In the `execute()` method you get access system values via the `HandlerUtil` class.

=== Validity of handlers
		
Handler can be defined with conditions (activeWhen) under which define the conditions under which the handlers are valid for a command.
You can define several handlers for a command.
Only one handler can be valid for a command for a certain condition.
If several handlers are valid, the Eclipse runtime does disable the command.
	
