== Asking (and answering) questions

Due to the complexity and extensibility of Eclipse, you will
need
additional resources to help you solve your specific
problems.
Fortunately, the web contains several resources which can help
you
with
your Eclipse problems.

Currently, the best places to find, ask and answer questions are the http://eclipse.org/forums[Eclipse forums] and http://stackoverflow.com[Stack Overflow]. 
Try to stay polite with your postings, as the Eclipse community values polite behavior.

The _Eclipse forums_ offer several topic-specific forums in which you can post and answer questions. 
To post or to answer questions in the Eclipse forums, you need a valid user account in the Eclipse bug tracker. 
_Stack Overflow_ also requires a user account and its community is very active.
_Stack Overflow_ allows to tag questions with the relevant keyword, e.g., _Eclipse_ and people search for them or subscribe to these theses.

[NOTE]
====
Ensure that you search the forums and mailing lists for solutions for your problem. 
Somebody else might has asked the same question earlier and the answer is already available.
====

