== Selection service

=== Usage of the selection service

The `ESelectionService` service allows you to retrieve and set the global selection in your current application window.
Other classes in the application model can use the dependency injection mechanism to retrieve the relevant active selection directly.

A client can get the selection service via `@Inject ESelectionService`.

TIP:The selection is window specific, i.e. stored in the context of the `MWindow` model object.

=== Changing the current selection

You can change the current selection with the `setSelection()` method of the `ESelectionService` class.
This is demonstrated in the following code.

[source,java]
----
include::res/servicesoverview/setSelection.java[]
----

=== Getting the selection

A client can retrieve the last selection for the current window directly from the `ESelectionService` via the `getSelection()` method.
The `getSelection(partId)` method allows you to retrieve the selection of a specific part.

TIP:The possibility of retrieving the selection of a part is based on the hierarchy of the `IEclipseContext`.
With this hierarchy it is possible to store a selection per window and also per part.

It is preferred that a class which is part of the application model uses dependency injection to retrieve the selection.
The selection is stored under the key based on the `IServiceConstants.ACTIVE_SELECTION` constant.
This key can be specified via the `@Named` annotation.
The Eclipse framework ensures that selections are only injected if they have the fitting type.

The usage of the `@Named` annotation to retrieve the selection is demonstrated with the following method.

[source,java]
----
include::res/servicesoverview/getSelection.java[]
----

