== Eclipse development good practices

=== Project, package and class names

It is good practice to use your reverse web domain
name as top-level
package identifier. For example if you own the
domain
_mycompany.com_
you package name space would start with
`com.mycompany`. 
This avoids name collision with packages contributed by other plug-ins.


The following table suggests good practices for naming
conventions for projects, packages and classes.

.Naming conventions
[cols="1,2",options="header"]
|===
|Object |Description

|Project Names
|The plug-in project name is the same as the top-level package name.

|Packages
|Plug-ins which contain a lot of user interface components use
sub-packages based on the primary purpose of the
components. For
example,
the
`com.example`
package
may have the
`com.example.parts`
and
`com.example.handler`
sub-package.

|Class names for model elements
|Use the primary purpose of the model element as a suffix in the
class
name. For example, a class used as a part
implementation,
should be called
`[PurposeDescription]Part`.
|===

=== Naming conventions for model identifiers (IDs)

Every model element allows you to define an ID. This ID is used
by
the Eclipse framework to identify this model
element. Make sure you
always maintain an ID for every model element and ensure that these
IDs are unique whenever it
makes sense. Reusing IDs is sometimes
required. For example you typically use the same ID for the main menu
in every
window of you application. This allows menu contributions to
contribute to every window its menu entries.

Unintentionally using the same ID for a model element may result
in unexpected behavior. For example if you
search for a element via
the ID.

A good convention is to start IDs with the
_top level package_
name of
your project followed by a group descriptor and a name which
gives an
idea about the purpose of the element. For
example,
_com.example.e4.rcp.todo.part.todooverview_, where
_com.example.e4.rcp.todo_
is the top level
package,
_part_
is the group
descriptor for all visible
parts (views and editors)
in
your
application and
_todooverview_
gives an
idea about the purpose of this
part.

Also note that the
entire
ID is
written only in lower case
characters.

Some
Eclipse projects also
use
camelCase for the last part of the
ID, but that is
more for historical reasons.

=== Create isolated components

It is important to separate your application components into isolated modules.
This reduces the complexity of development and allows you to reuse these components in different applications.

User interface related and core functionalities should be separated into different plug-ins. 
For example, if you develop a new SWT widget, you should place this widget in a separate plug-in.

The data model of the application should be kept in its own plug-in. 
Almost all application plug-ins will depend on this plug-in, therefore keep it as small as possible.

=== Usage of your custom extension points

The programming model of Eclipse 4.x API has reduced the need for using extensions and extension points.
But custom extension points still have valid use cases.

If you have multiple plug-ins which should contribute to a defined API, you can still define and use your own extension points.

=== Avoid releasing unnecessary API

Eclipse plug-ins explicitly declare their API via their exported
packages. Publish only the packages which other
plug-ins should use.
This
way you can later on change your internal API without affecting
other plug-ins.
Avoid
exporting
packages just for testing.

=== Packages vs. plug-in dependencies

OSGi allows you to define dependencies via plug-ins (Require-Bundle) or via packages (Import-Package) in the manifest file.

Dependencies based on packages express an API dependency, as they allow you to exchange the implementing plug-in.
Dependencies based on plug-ins imply a dependency on an implementation.

Prefer the usage of package dependencies whenever you intend to exchange the implementing plug-in.

Package dependencies add some complexity to the setup as you usually have more packages than plug-ins.
Therefore some people use plug-in dependencies, if there is only one implementing plug-in and an exchange of this plug-in in the near future is unlikely.

