
== Rebase


=== Rebasing a branch onto another

Now do a rebase of the conflicting commit instead of a merge. 

Checkout the second feature branch.

Use the `git rebase` command to rebase the second feature branch onto the first one.
				
				
The rebase stops because of a conflict. Resolve this merge conflict and use `git rebase --continue` to continue the rebase.

Use the `git log` command to view the created history.
				
Note that there is a reference called `ORIG_HEAD` pointing to the commit which was checked out before the rebase operation. 
You may revert the rebase operation with reset as described above.



=== Using interactive rebase to edit the commit message
		
Use `git rebase -i HEAD~4`.

Reword one of your commit messages.


=== Squash two commits

Do another commit by adding a comment in the code to your last change. Commit this change via a new commit.
		
You realize that you wanted to combine the last two commits. Use Use the `git rebase -i` command to combine both commits.
		

=== Remove a commit
		
Do two more commits, A followed by B. 
You want to remove the commit A from your history. 
Use the interactive rebase to perform this operation.
		
