== Testing Eclipse 4 application

=== General testing

In general all Java classes in an Eclipse 4 application can be tested similarly to other Java applications. 
This description highlights the special Eclipse 4 constructs.


=== Fragment projects
(((Fragment projects,Tests)))

Tests for Eclipse plug-ins are typically contained in a fragment project. 
This way the tests can access all classes in their host plug-in.


=== Testing user interface components
(((Testing,User interface components)))

Eclipse classes that are using the application model have no hard dependency on the Eclipse framework. 
Therefore you can test these components directly with JUnit.


For example take the following part.


[source,java]
----
include::res/snippets/TodoOverviewPart.java[]
----

This part can be created via a simple Java Program which has the SWT library included in its classpath.


[source,java]
----
include::res/snippets/TodoOverviewPartTest.java[]
----

The above code can be easily changed to a unit test. 
Your test class can create the class, provide the required dependencies and run the tests.


=== Testing dependency injection
(((Testing,Using dependency injection in your tests)))

You can include the process of dependency injection into the test.
Create your own `IEclipseContext` and use the `ContextInjectionFactory.make()` method to create the object which should be tested.


The following code shows an example of how to create your own context and construct the object based on this construct. 
This test needs to run as _JUnit Plug-in_ test.


[source,java]
----
include::res/snippets/CreateContextText.java[]
----


