==  Using features

=== What are feature projects and features?
	
Using the Eclipse wizards you can create feature projects, similarly on how you create plug-in projects.
An
Eclipse
feature project contains
_features_.
	
A
feature
describes a list of plug-ins and other features which can
be
seen
as a logical
unit, i.e., a set of related
components. It also has a
name,
a version number and
in most cases a license information assigned to it.
	
A
feature
is described via a
_feature.xml_
file. The following listing shows an example of such a file.
	
[source,xml]
----
include::res/feature.xml[]
----
	
=== Advantages of using features

The grouping of plug-ins into logical units makes it easier to
handle a set of plug-ins. Instead of adding many
individual plug-ins
to
your product configuration file, you can group
them using features. That
increases the visibility
of your application
structure.

Features can be consumed by the Eclipse update
manager,
the
build
process
and optionally for the definition of Eclipse
products.
Features
can
also be
used as basis to define a launch
configuration.

Eclipse provides several predefined features, e.g.
the
`org.eclipse.e4.rcp`
for Eclipse RCP applications.

=== Feature or plug-in based products
    
A product can either be based on plug-ins or on features.
This setting is done on the _Overview_ tab of the product configuration file.
    
On the
_Contents_
tab in the product editor you enter the plug-ins or features
your
products consists of.
    
A
product does not perform automatic
dependency
resolution. If you add a
feature
to your product
and want to
add its
dependencies, press the
_Add Required_
button.


=== Creating a feature

You can create a new feature project via the following menu path:
menu:File[New > Other... > Plug-in Development > Feature Project].

    
If you open the
_feature.xml_
file you can change the feature
properties via a special editor.
    
The
_Information_
tab allows you to enter a description and copyright related
information for this feature.
    
The
_Included Plug-ins_
tab
allows you to change the included plug-ins
in
the feature. If you want to add a plug-in to a feature, use this
tab. A
frequent error of new Eclipse developers is to add it to the
_Dependencies_
tab.
    
The
_Included Features_
tab allows you to include other features into this feature. Via the
_Dependencies_
tab you can define other features which must be present to use this
feature.
    
The
_Build_
tab is used for the build process and should include the
_feature.xml_
file. The last two tabs give access to the configuration files in text
format.

	