
== Using layout managers in SWT

=== The role of a layout manager
		
		
		
		
		
		
		<indexterm>
			<primary>SWT</primary>
			<secondary>Layout manager</secondary>
		</indexterm>
		
			A layout manager is
			responsible for arranging the user interface
			components
			of a
			container, e.g., a
			`Composite`
			,
			on
			the
			screen.
			SWT
			offers several standard layout managers. The
			following table gives an overview of them. It is sorted
			by complexity
			of the layout manager,
			i.e. the simplest layout manager is listed
			first and the most complex one as the
			last entry.

			<table frame='all'>
		=== Layout Manager
				<tgroup cols='2' align='left' colsep='1' rowsep='1'>
					<colspec colname='c1' colwidth="1*" />
					<colspec colname='c2' colwidth="2*" />
					<thead>
						<row>
							<entry>Layout Manager</entry>
							<entry>Description</entry>
						</row>
					</thead>
					<tbody>
						<row>
							<entry>AbsoluteLayout</entry>
							<entry>Allows you to specify the exact position, the width and
								the height of
								components. As user interfaces may be
								used on
								screens
								with
								different
								sizes this layout manager should be avoided.
							</entry>
						</row>
						<row>
							<entry>FillLayout</entry>
							<entry>Arranges
								equal-sized widgets in a
								single row or
								column.
							</entry>
						</row>
						<row>
							<entry>RowLayout</entry>
							<entry>Puts the widgets in rows or columns and allows you to
								control the layout with options, e.g., wrap, spacing,
								fill and so
								on.
							</entry>
						</row>
						<row>
							<entry>GridLayout</entry>
							<entry>Arranges widgets in a
								grid.
							</entry>
						</row>
						<row>
							<entry>FormLayout</entry>
							<entry>Arranges the widgets with the help of the associated
								attachments.

							</entry>
						</row>
					</tbody>
				</tgroup>
			</table>
		
		
			If you assign a layout manager to a control you do not have to call
			`pack`
			anymore. The only case in which you need to call
			`pack`
			is if control has no layout.
		
	

=== Layout Data
		

			Each SWT widget can have a layout specific settings class assigned to
			it, e.g.
			`GridData`
			for a
			`GridLayout`
			. This allows the developer to control the arrangement of the widgets
			within the layout.
		
		
			In the following example you specify that a certain widget
			should take
			two columns in a
			`GridLayout`
			.
		
		
			<programlisting>
				<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" parse="text" href="./examples/gridlayout/gridDataExample.txt" />
			</programlisting>
		
		<warning>
			
				The used
				layout data
				must match the
				layout manager,
				otherwise an
				exception is thrown at
				runtime.
			
		</warning>
		
			The layout will be automatically calculated when the container is
			displayed. You can tell a
			`Composite`
			to recalculate the layout with the
			`composite.layout()`
			method.
		
		<warning>
			
				Layout data
				objects should not be reused as the
				layout
				manager
				expects that every user interface
				element has a
				unique
				layout
				data
				object.
			
		</warning>
	

=== FillLayout
		
			`FillLayout`
			divides the available space provided by the container equally to all
			widgets and can be set to
			arrange the widgets
			either
			horizontally (
			`SWT.HORIZONTAL`
			)
			or vertically (
			`SWT.VERTICAL`
			). It also allows you to set the space between the widgets (attribute
			`spacing`
			) and the margins of the widgets to the container via the
			`marginWidth`
			and
			`marginHeight`
			attributes.
		


	

=== RowLayout
		
			`RowLayout`
			orders UI components in a row (
			`SWT.HORIZONTAL`
			) or in a
			column (
			`SWT.VERTICAL`
			).
			`RowLayout`
			supports wrapping of
			fields (field
			`wrap`
			) by default. You can define if widgets should have their
			preferred
			size
			(default)
			or if they should grab the available
			space
			via the field
			`pack`
			. It is also possible to set margins at the top, bottom, left and
			right. If you
			set
			`justify`
			, the widgets will be spread through
			the
			available space.
		
		
			Each element can define its height and width via a
			`RowData`
			element.
		
	

=== GridLayout
		
			`GridLayout`
			allows you to arrange the user interface components in a Grid with a
			certain number of columns. It is also possible to
			specify column and
			row
			spanning.
		

		
			You can use
			`new GridData()`
			and assign properties to the new object. Alternatively you can use
			one of its richer constructors to define certain
			attributes during
			construction. For example via the following constructor.
		

		
			<programlisting language="java">
				<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" parse="text" href="./examples/gridlayout/Constructor.java" />
			</programlisting>
		

		
			The most important attributes are defined in the following table.

			<table frame='all'>
		=== GridData
				<tgroup cols='2' align='left' colsep='1' rowsep='1'>
					<colspec colname='c1' colwidth="1*" />
					<colspec colname='c2' colwidth="2*" />
					<thead>
						<row>
							<entry>Parameter</entry>
							<entry>Description</entry>
						</row>
					</thead>
					<tbody>
						<row>
							<entry>horizontalAlignment</entry>
							<entry>
								Defines how the control is positioned horizontally
								within a
								cell
								(one
								of:
								`SWT.LEFT`
								,
								`SWT.CENTER`
								,
								`SWT.RIGHT`
								, or
								`SWT.FILL`
								).
							</entry>
						</row>
						<row>
							<entry>verticalAlignment</entry>
							<entry>
								Defines how the control is
								positioned vertically within a
								cell
								(one
								of:

								`SWT.TOP`
								,
								`SWT.CENTER`
								,
								`SWT.END`
								,
								`SWT.BOTTOM`
								(treated the same as SWT.END), or
								`SWT.FILL`
								).
							</entry>
						</row>
						<row>
							<entry>grabExcessHorizontalSpace</entry>
							<entry>Defines whether the control is
								extended by the layout
								manager to
								take all
								the
								remaining
								horizontal space.
							</entry>
						</row>
						<row>
							<entry>grabExcessVerticalSpace</entry>
							<entry>Defines whether the control grabs any remaining vertical
								space.
							</entry>
						</row>
						<row>
							<entry>horizontalSpan</entry>
							<entry> Defines the number of column cells
								that the control will
								take
								up.
							</entry>
						</row>
						<row>
							<entry>verticalSpan</entry>
							<entry>Defines the number of row cells that
								the control will take
								up.
							</entry>
						</row>
						<row>
							<entry>heightHint </entry>
							<entry>Defines the preferred height in pixels.
							</entry>
						</row>
						<row>
							<entry>widthHint  </entry>
							<entry>Defines the preferred width in pixels.
							</entry>
						</row>
					</tbody>
				</tgroup>
			</table>
		
		
			If the widget has the
			`grabExcessHorizontalSpace`
			attribute set to true, it will grab available space in its container.
			`SWT.FILL`
			tells the widget to fill the available space.
			Therefore,
			`grabExcessHorizontalSpace`
			and
			`SWT.FILL`
			are often used together.
		
		<tip>
			
				The
				`GridDataFactory`
				class provides static methods for creating
				`GridData`
				objects. The Javadoc of this class contains several examples for it.
			
		</tip>



	

=== Using GridDataFactory
		
			The
			`GridDataFactory`
			class can be used to create
			`GridData`
			objects. This class provides a convenient shorthand for creating and
			initializing GridData. The following listing
			demonstrates its usage
			and compares it with the direct usage of
			`GridData`
			.
		
		
			<programlisting language="java">
				<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" parse="text" href="./examples/gridlayout/GirdDataFactory.java" />
			</programlisting>
		


		
			Unfortunately the
			_SWT Designer_
			does currently not support
			`GridDataFactory`
			, hence the following examples avoid using them.
		
	

=== Triggering a relayout of a Composite
		
			The
			`Composite`
			widget defines the
			`layout`
			method. This method accepts also child widgets and flags. These flags should rarely be used in client code.
		
		<table frame='all'>
	=== Layout flags
			<tgroup cols='2' align='left' colsep='1' rowsep='1'>
				<colspec colname='c1' colwidth="1*" />
				<colspec colname='c2' colwidth="2*" />
				<thead>
					<row>
						<entry>Flag</entry>
						<entry>Description</entry>
					</row>
				</thead>
				<tbody>
					<row>
						<entry>SWT.ALL</entry>
						<entry>Flag forces all descendents to be marked for layout. AFAIK, there's no good reason to ever use this
							flag.
							If it's actually doing something, it could be replaced by a series of calls to requestLayout.
						</entry>
					</row>
					<row>
						<entry>SWT.CHANGED</entry>
						<entry>The flag causes
							subsequent calls to
							Layout.layout(...) to receive true for the second argument, which
							forces
							the layout to recursively
							flush all caches.
							There's no good reason to ever do this. If something changed, the
							layout should have been notified
							via
							Layout.flushCache(control) (which is what happens when you invoke
							requestLayout). This is either a brute-force
							workaround for a stale layout bug or was just unnecessary.
							I can't
							think of any circumstance in which we should keep
							SWT.CHANGED.
						</entry>
					</row>
					<row>
						<entry></entry>
						<entry></entry>
					</row>
				</tbody>
			</tgroup>
		</table>


		-



	
	