== Migration to Eclipse 4

=== Migration to Eclipse 4
		
If you want to migrate your Eclipse 3.x RCP application to the
Eclipse
4 programming model, you can't directly reuse existing
_plugin.xml_
based user interface components, e.g.
views
or
editors
based on the
definition in
_plugin.xml_
.
		
		
Migrating such components would involve:

* Converting existing user interface contributions via extension points to the application model.
* Removing the usage of Singleton objects from the Eclipse platform, e.g. `Platform` or `PlatformUI` and use the dependency injection programming model.
		
=== Using 3.x components in Eclipse 4 applications
		
Mixing Eclipse 4.x and Eclipse 3.x. components is currently not
officially supported.

=== Reuse of platform components
		 
Most Eclipse IDE components are still based on the Eclipse 3.x API.
The Eclipse platform plans to migrate more and more existing
components
to the Eclipse 4.x API over time. For customers this means
that certain components which could be reused in Eclipse 3.x RCP
application are not available by default.
		
Currently most
components, for example, the IDE perspective switcher,
the
view switcher,
the
_Progress_
view, the new project wizard are based on the Eclipse 3.x API and
therefore cannot be used without modifications in an Eclipse 4 RCP
application.

=== Replacements for 3.x components for Eclipse 4.x applications
		
The
http://www.vogella.com/company/index.html - vogella GmbH
provides an Open Source project for an e4 based
perspective switcher.
See the following URL for details:
https://github.com/vogellacompany/e4dashboard-perspective-switcher 
		
The Eclipse platform team provides also an Eclipse 4 based progress
view. See the following URL for details:
https://wiki.eclipse.org/Eclipse4/ProgressView
	
