== Editing
The following lists contains useful keyboard shortcuts if you are inside your Java editor.

.Table Handling the editor
|===
|Shortcut |Description

|Ctrl + 1
|Quickfix; result depending on cursor position

|Ctrl + Space
|Content assist/ code completion

|Ctrl + T
|Show the inheritance tree of the current Java class or method.

|Ctrl + O 
|Show all methods of the current class, press Ctrl + O again to show the inherited methods.

|Ctrl + M
|Maximize active editor or view

|Ctrl + Shift + F
|Format source code

|Ctrl + I
|Correct indentation, e.g.,  format tabs/whitespaces in code 

|Ctrl + F
|Opens the find dialog  

|Shift + Enter
|Adds a link break at the end of the line

|Ctrl + Shift + O
|Organize the imports; adds missing import statements and removes unused ones

|kbd:[Alt+Shift+Z] 
| Wrap the select block of code into a block, e.g. try/catch.

|===


<table frame='all'>
=== Cursor navigation and text selection
<tgroup cols='2' align='left' colsep='1' rowsep='1'>
<colspec colname='c1' colwidth="1*" />
<colspec colname='c2' colwidth="3*" />
<thead>
<row>
Shortcut
Description
</row>
</thead>
<tbody>
<row>
Ctrl + &#8592; or Ctrl + &#8594;
Move one text element in the editor to the left or right

</row>
<row>
Ctrl + &#8593; or &#8595; 
Scroll up / down a line in the editor
</row>

<row>
Ctrl + Shift + P
 Go to the matching bracket
</row>
<row>
Shift + Cursor movement
Select text from the starting position of the cursor

</row>

<row>
Alt + Shift &#8593; / &#8595;
Select the previous / next syntactical element
</row>
<row>
Alt + Shift  &#8593; / &#8595; / &#8592; / &#8594;
Extending / reducing the selection of the previous / next
syntactical element

</row>

</tbody>
</tgroup>
</table>





<table frame='all'>
=== Copy and move lines
<tgroup cols='2' align='left' colsep='1' rowsep='1'>
<colspec colname='c1' colwidth="1*"/>
<colspec colname='c2' colwidth="3*"/>
<thead>
<row>
Shortcut
Description
</row>
</thead>
<tbody>
<row>
Ctrl + Alt + &#8595; 
Copy current line below the line in which the cursor is
placed

</row>

<row>
Ctrl + Alt + &#8593;
Copy current line above the line in which the cursor is
placed

</row>

<row>
Alt + Up  
Move line one line up
</row>
<row>
Alt + Down 
Move line one line down
</row>
</tbody>
</tgroup>
</table>



<table frame='all'>
=== Delete
<tgroup cols='2' align='left' colsep='1' rowsep='1'>
<colspec colname='c1' colwidth="1*"/>
<colspec colname='c2' colwidth="3*"/>
<thead>
<row>
Shortcut
Description
</row>
</thead>
<tbody>

<row>
Ctrl + D
Deletes line
</row>
<row>
Ctrl + Shift + DEL
Delete until end of line
</row>
<row>
Ctrl + DEL
Delete next element
</row>
<row>
Ctrl + BACKSPACE
Delete previous element
</row>
</tbody>
</tgroup>
</table>


<table frame='all'>
=== Create new lines
<tgroup cols='2' align='left' colsep='1' rowsep='1'>
<colspec colname='c1' colwidth="1*"/>
<colspec colname='c2' colwidth="3*"/>
<thead>
<row>
Shortcut
Description
</row>
</thead>
<tbody>
<row>
Shift + Enter 
Adds a blank line below the current line and moves the
cursor to the
new line. The difference between a regular enter is
that the currently line is unchanged, independently of the
position of the cursor.

</row>

<row>
Ctrl+Shift+Enter 
Same as Shift + Enter but above

</row>
</tbody>
</tgroup>
</table>



<table frame='all'>
=== Variable assignment
<tgroup cols='2' align='left' colsep='1' rowsep='1'>
<colspec colname='c1' colwidth="1*"/>
<colspec colname='c2' colwidth="3*"/>
<thead>
<row>
Shortcut
Description
</row>
</thead>
<tbody>

<row>
Ctrl + 2, L
Assign statement to new local variable
</row>
<row>
Ctrl + 2, F
Assign statement to new field 
</row>

</tbody>
</tgroup>
</table>




