== WorkbenchParts and Perspectives

=== WorkbenchParts - Views and Editors

As described earlier the
`WorkbenchWindow`
and the
`WorkbenchPage`
represent the visual and inner part of the graphical user interface.

The
`WorkbenchPage`
contains Parts, which can be
_Views_
or
_Editors_.

_Views_
are used to display information in an RCP application; they
can also
be used to change data.
_Views_
extend the abstract class
`ViewPart`
.
_Editors_
extend the abstract
`EditorPart`
. Both extend
`WorkbenchPart`.

An
`editor`
typically requires that the user explicitly select "save" to apply
the
changes to the data while a view typically changes the data
immediately.

All editors are opened in the same area. Via the
perspective you can
configure if the editor area is visible or not.

_Views_
and
_Editors_
are defined via extension points in the file _plugin.xml_ via the tab
"Extensions".

_Views_
are defined via the extension point "org.eclipse.ui.views"
and
_Editors_
via the extension point "org.eclipse.ui.editors".

_Views_
must implement the
`createPartControl()`
and
`setFocus()`
methods.

`createPartControl()`
is used to create the UI components of the
`View`
.

createPartControl() will get as parameter a
`Composite`
which can be used to construct the user interface. This composite
has
by default a
`FillLayout`
layout manager assigned to it. This layout manager assigns the same
space to all components
equally.

`setFocus()`
must set the focus to a specific UI component.




=== Perspective

A
`Perspective`
describes a certain configuration of
_Views_
and
_Editors_
.


A
`Perspective`
is defined via "org.eclipse.ui.perspectives". The
`WorkbenchParts`
which are part of a
`Perspective`
are either defined via a Java class defined in the extension point
"org.eclipse.ui.perspectives" or via the
"org.eclipse.ui.perspectiveExtensions".


[source,text]
----
include::res/perspective/addView.txt[]
----

`layout.addView()`
adds a view to the perspective.

You can also add placeholders for
views
via the
`layout.addPlaceholder()`
method call. This methods accepts wildcards and a
`View`
with a matching ID would open in this area. For example if you want
to open all views in a specific place you could use the
`layout.addPlaceholder("*",...)`
method call, or

`layout.addPlaceholder("view_id",....)`
to open a View with the "view_id" ID in this placeholder.

You can also group view via a
`IFolderLayout`
which can be created via
`layout.createFolder()`
call and by adding
_Views_
to this folder via the
`addView(id)`
method on
`IFolderLayout`
.

