== WorkbenchAPI

TointeractwiththeWorkbenchyouhaveaccesstotheWorkbench
API.Forexampleyoucanaccesstheactiveeditororviewandopenor
closeViewsandEditors.

MostAPIcallsaredoneviatheWorkbenchPage.
AcommandhandlercangetaccesstotheWorkbenchPagevia:

[source,text]
----
include::res/workbench/handler.txt[]
----

AviewprovidesaccesstotheWorkbenchandtheWorkbenchWindow
viathegetViewSite()method.Aneditorprovidesthesameaccessvia
getEditorSite().

[source,text]
----
include::res/workbench/view.txt[]
----

[source,text]
----
include::res/workbench/editor.txt[]
----

YoucouldalsogettheWorkbenchpageoverthePlatformUI
Singleton.

[source,text]
----
include::res/workbench/platformui.txt[]
----

OnceyouhaveaccesstothePageyoucancallitsAPI.The
followingdemonstrateshowtofirstcloseallviewsintherunning
applicationandhowtoopenaViewwithaspecificID.

[source,text]
----
include::res/workbench/example.txt[]
----

Thefollowingshowshowtosaveaneditorandhowtocloseit.

[source,text]
----
include::res/workbench/close.txt[]
----

YoucanalsoaddaPartListenertothepageandlistenfor
changeinViewandEditors.Hereisanexamplehowtoaddsucha
listenerinApplicationWorkbenchWindowAdvisor.

[source,text]
----
include::res/workbench/ApplicationWorkbenchWindowAdvisor.txt[]
----

