== Recipes

This chapter contains a few recipes for typical development tasks and some additional background material.

=== Reading resources from plug-ins
	
You can access files in your plug-in via two different approaches: 

* via the `FileLocator` class or 
* via an Eclipse specific URL. 

Both approaches require that your plug-in defines a dependency to the `org.eclipse.core.runtime` plug-in.
	
Both approaches return a URL which can be used to get an `InputStream`.
	
The following code shows an example with `FileLocator`.

[source,java]
----
Bundle bundle = FrameworkUtil.getBundle(this.getClass());
URL url = FileLocator.find(bundle, 
    new Path("path_to_file"), null);

----
	
The following code shows an example for the usage of the Eclipse specific URL.

[source,java]
----
URL url = null;

try {

  url = new URL("platform:/plugin/" 
    + "your_bundle-symbolicname"
    + "path_to_file");
    
    } catch (MalformedURLException e1) {
      e1.printStackTrace();
}
----
	
Using the URL to create an `InputStream` and to read the file is demonstrated in the next code example.
	
[source,java]
----
public static String readTextFile(URL url) throws IOException {
    StringBuilder output = new StringBuilder();
    String lineSeperator = System.lineSeparator();

    try ( InputStream in = url.openConnection().getInputStream();
          BufferedReader br = new BufferedReader(new InputStreamReader(in)) ) {
        
        String inputLine;

        while ((inputLine = br.readLine()) != null ) {
            output.append(inputLine).append(lineSeperator);
        }

      if (output.length()>0) {
        // remove last line separator
        output.setLength(output.length() - lineSeperator.length());
      }
     }

    return output.toString();
}
----	

[[recipes_loadimage]]
=== Loading images from a plug-in

The `ImageDescriptor` class has a static method to create an `ImageDescriptor` instance directly from a URL.
`ImageDescriptor` is a light-weight representation of an `Image`.
Via the `createImage()` you can create the `Image` instance.

[source,java]
----

@Override
public Image loadImage(Class<Object> clazz, String path) {
    Bundle bundle = FrameworkUtil.getBundle(this.getClass());
    URL url = FileLocator.find(bundle, 
        new Path("icons/alt_window_32.gif"), null);

    ImageDescriptor imageDescr = ImageDescriptor.createFromURL(url);
    return imageDescr.createImage(); 
}
----



