== Eclipse Editors


=== Overview

Eclipse uses editors and views to maintain data.
An editor typically requires that the user explicitly select "save" to apply the changes to the data while a view typically changes the data immediately.

All editors are opened in the same area.
Via the perspective you can configure if the editor area is visible or not.


=== Steps required to create an editor

The following steps are required to create and use an editor within an RCP application.

* Make the editor area visible in your perspective
* Create an IEditorInput class
* Define an extension for the "org.eclipse.ui.editors" extension point
* Implement the class for the editor, this class must implement IEditorPart


=== IEditorInput

IEditorInput serves as the model for the editor and is supposed to be a light-weight representation of the model.
Eclipse will buffer IEditorInput objects therefore this object should be relatively small.

For example the Eclipse IDE uses IEditorInput objects to identify files without handling with the complete file.

Based on the equals() method of the IEditorInput the system will determine if the corresponding editor is already open or if a new editor must be opened.


=== IEditorPart and EditorPart

The editor is defined via the extension point "org.eclipse.ui.editors".
The class which implement the editor must implement the interface "IEditorPart".
In most cases it extends the abstract class "EditorPart".

The editor receives the IEditorSite and the IEditorInput in the init() method.
It must set the input via the setInput() method and the side via the setSite() method.

init() is called before createPartControl() therefore you can use the input during your UI creation (which happens in createPartControl()).


=== Setting the Editor Title and Tooltip

By default the editor will use the tooltip and title from the `IEditorInput`.

Typically the EditorInput is only a light-weight representation of the real object.
Therefore you may want to change the title and tooltip in your Editor.
Use setPartName() to set the title of the Editor.
To set the tooltip you have to override the method getTitleToolTip() (despite the Javadoc description).
See Bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=107772[https://bugs.eclipse.org/bugs/show_bug.cgi?id=107772] for details.


=== Saving the Editor Content

In an editor the method isDirty() is used to inform the workbench if the content of the editor is changed.
For inform the workbench that the dirty property of the editor has changed you fired an event.

[source, java]
----
include::./res/save/change.txt[]
----


=== Editor area

In a standalone RCP application you can make the editor area visible by changing your Perspective.java.

[source, java]
----
include::./res/editor/Perspective.java[]
----


=== API for working with Editors

You can open an Editor via the current active page.
For this you need the EditorInput object and the ID for the editor which is defined in the "org.eclipse.ui.editors" extension point.

[source, java]
----
include::./res/api/openeditor.txt[]
----

To get the page you can use:

[source, java]
----
include::./res/api/page.txt[]
----

