== Define a project nature

Project natures are defined with the `org.eclipse.core.resources.natures`
extension point.
A bare project nature only needs a name, id and a class reference, which implements
`IProjectNature`.

[source,xml]
----
include::res/bare_projectnature.xml[]
----

The implementation of the referenced `ExampleProductNature` can look like
this:

[source,java]
----
include::res/ExampleProjectNature.java[]
----

NOTE: The acutal id of a project nature consists of the
_Bundle-SymbolicName_ + _id_, which is
defined for the extension point. See _NATURE_ID_ in
`ExampleProductNature`.


=== Require a certain project nature as precondition
In some cases applying a project nature only makes sense, if the project already has a certain project nature.
For example your custom project nature should only apply for Java project.

[source,xml]
----
include::res/requires_projectnature.xml[]
----

=== Get and set a Project Natures
Every `IProject` has an `IProjectDescription`, which contains
all _natureIds_.

[source,java]
----
include::res/GetAndSetProjectNatures.java[]
----

=== Using expressions to check for project natures
The existence of a certain project nature can also be checked with a core expression,
which can be defined within the `org.eclipse.core.expressions.definitions`
extension point.

[source,xml]
----
include::res/core_expression_projectnature.xml[]
----

Here you can see that a `PropertyTester` for project natures is already
available and you can use the
_org.eclipse.core.resources.projectNature_ property to check
for a certain project nature.

