== Contributing to the Eclipse open source project

=== Code contributing
		
Eclipse projects are an open source projects. Multiple developers - companies and individuals alike - advance the code.
Everyone has read access to the code repositories hosted at eclipse.org.
It is possible for you to get the source code, modify it and provide the change back to the project. 
Most Eclipse projects use a code review process based on the Gerrit code review system, some use Github.
		
Contributing to an Eclipse project has the benefit of getting feedback directly from the core developers. 
It also allows developers and organizations to fix bugs which affect them and to drive the project into a desired direction.
		
This {textselfreference} focuses on the process of contributing code to an Eclipse project.
If case you do not want to contribute code, there are other ways of contributing.
For example, you can provide or update documentation for a project wiki.
	
=== Users, Contributors and Committers
		
The Eclipse project distinguishes between the following group of people:

* Eclipse User - Using at least one product, e.g., a _JAR_ file, of the Eclipse project. Eclipse users consume the software created by the Eclipse developers. 
Users also report bugs and issue feature requests in Eclipse projects they are using.
	
* Contributors are individuals who contribute code fixes or make other significant contributions to the project.
	
* Committers have write access to the project's resources (source code repository, bug tracking system, website, build server, downloads, etc.) and are expected to influence the project's development.
		
=== Relevant Eclipse projects

Eclipse hosts multiple projects but several projects are critical for the development of the Eclipse IDE and RCP applications. 
These are described here.
        
==== The Eclipse Platform project

(((Platform project)))
The _Eclipse Platform_ project provides the core frameworks and services upon which all Eclipse based applications are created. 
It also provides the runtime in which Eclipse components are loaded, integrated, and executed. 
The primary purpose of the _Eclipse Platform_ project is to enable other developers to easily build and deliver integrated tools and applications.

==== The Eclipse Plug-in Development Environment (PDE)

(((PDE)))
((((Plug-in Development Environment)))
The Eclipse Plug-in Development Environment (PDE) project provides wizards for creating Eclipse RCP applications and plug-ins, editors and other tools to develop Eclipse plug-ins.

        
==== The Eclipse e4 project

((((e4 project)))
_Eclipse e4_ is the name used for the _Eclipse Platform_ incubator project.
This incubator is used for exploratory projects relating to improving the Eclipse Platform.

The e4 project includes several technology evaluations.
Some of these evaluations have been ported back to the core Eclipse framework.
All functionalities described in this document are part of the official Eclipse release, except the _Eclipse e4 tooling_ project.

The _Eclipse e4 tooling_ project provides tools for developing Eclipse 4 applications. 
They are very useful, but have not yet been added to any main Eclipse  project.
	

