== The Eclipse foundation and the Eclipse public license

=== Eclipse foundation

The Eclipse projects are governed by the _Eclipse Foundation_.
The Eclipse Foundation is a non-profit, member supported corporation that hosts the Eclipse Open Source projects.
It helps to cultivate both its open source community and its ecosystem of complementary products and services.


The Eclipse Foundation does not work on the Eclipse code base, i.e., it does not have employee developers working on Eclipse.
The mission of the Eclipse Foundation is *enable* the development by providing the infrastructure (Git, Gerrit, Hudson build server, the download sites, etc.) and a structured process. 
Eclipse projects follow a very well defined development process. 
To learn more about this process see the http://www.eclipse.org/projects/dev_process/development_process.php[Eclipse development process description].


There is also an https://www.eclipse.org/org/press-release/20131029_efe_faq.php[Eclipse Foundation Europe] based in Germany. 

In 2016 the Eclipse Foundation had approximately 30 employees. See http://www.eclipse.org/org/foundation/staff.php[Eclipse Foundation Staff] for details.


=== The Eclipse Public License



The _Eclipse Public License_ (EPL) is an open source software license.
The EPL is designed to be business-friendly. 
EPL licensed programs can be used, modified, copied and distributed free of charge. 
The consumer of EPL-licensed software can choose to use this software in closed source programs.

Only modifications in the original EPL code must be released as EPL code. 
This can for example be done by filling a bug report at the public Eclipse bug tracker and by uploading a Gerrit change.


The Eclipse Foundation validates that source code contributed to Eclipse projects is free of intellectual property (IP) issues. 
This process is known as IP cleansing. 
Contributions with more than 1000 lines of code require the creation of a Contribution Questionnaire, and a review and approval by the IP team.


The permissive EPL and the IP cleansing effort of the Eclipse Foundation makes reusing the source code of Eclipse projects attractive to companies.

