== Eclipse projects responsible for the Java IDE

=== The Eclipse project

The Eclipse IDE is an open source (OS) project. 
Eclipse.org hosts lots of OS projects with different purposes. 
The foundation of the whole Eclipse IDE is delivered by the Eclipse platform, the Java development tools (JDT) and the Plug-in Development Environment (PDE) project.

All these projects belong to the project called "Eclipse project". 
The name is a bit strange since nowadays there are many Eclipse projects. 
But it originates from the fact that these projects were at the beginning the only available Eclipse projects.


These components are bundled together as the Eclipse Standard Development Kit (SDK) release.
This is also known as the Eclipse standard distribution. 
The Eclipse SDK contains all tools to develop Eclipse plug-ins.


In addition to these projects, the platform also has an incubator project called _e4_ which provides new tools for Eclipse 4 developments. 
It also serves as a testing ground for new ideas.

=== The Eclipse platform projects home pages and Git repositories

The following table lists the home pages of these projects along with the developer pages, which list the Git (and Gerrit) repositories.


.Eclipse projects
[cols="1,2,3",options="header"]
|===
|Project |Home page | Developer pages with Git repositories

|Platform
|http://www.eclipse.org/eclipse/
|Not relevant, as platform is only the top project

|Platform UI
|https://www.eclipse.org/eclipse/platform-ui/
|https://projects.eclipse.org/projects/eclipse.platform.ui/developer

|Java development tools (JDT)
|http://www.eclipse.org/jdt
|https://projects.eclipse.org/projects/eclipse.jdt.ui/developer
https://projects.eclipse.org/projects/eclipse.jdt.core/developer

|Plug-in Development Environment (PDE)
|http://www.eclipse.org/pde
|https://projects.eclipse.org/projects/eclipse.pde/developer

|===

	


