== Update strategy, converters and validators

=== UpdateValueStrategy

The
`bindValue()`
method from
`DataBindingContext`
allows you
to specify
`UpdateValueStrategy`
objects as third and fourth parameters. These objects allow you to
control
how and when the values are updated. The
following values are permitted:

.UpdateValueStrategy
|===
|Value |Description

|`UpdateValueStrategy.POLICY_NEVER`
|Policy constant denoting that the source observable's state should not be
tracked and that the destination
observable's value should never be updated.

|`UpdateValueStrategy.POLICY_ON_REQUEST`
|Policy constant denoting that the source observable's state should not be
tracked, but that validation,
conversion and updating the destination observable's value should be performed when
explicitly requested. You can
call
`DataBindingContext.updateModels()`
or
`DataBindingContext.updateTargets()`
to update all bindings at once. Or you can call
`Binding.updateTargetToModel()`
or
`Binding.updateModelToTarget()`
to update a
single binding.

|`UpdateValueStrategy.POLICY_CONVERT`
|Policy constant denoting that the source observable's state should be
tracked, including validating changes
except for validateBeforeSet(Object), but that the destination observable's
value should only be updated on
request.

|`UpdateValueStrategy.POLICY_UPDATE`
|Policy constant denoting that the source observable's state should be
tracked, and that
validation,
conversion and
updating the destination observable's value should be performed
automatically on every
change of the
source
observable value.

|===

If no
`UpdateValueStrategy`
is specified, the
`UpdateValueStrategy.POLICY_UPDATE`
is used by default.
You can register converters and validators in the
`UpdateValueStrategy`
object.

=== Converter
(((JFace Data Binding,Converter)))

_Converters_
allow to convert the values between the observed properties. Converters are defined based on the
`IConverter`
interface.

`UpdateValueStrategy.setConverter()`
allows to set the converter.
The
`IConverter.create(Object, Object, Function)`
allows to create a converter using a lambda
expression. The static
`UpdateValueStrategy.create(IConverter)`
method allows to create
an update strategy with a converter.

For example, you can convert a String to another object and vice versa.

For example, assume you have a
`Person`
object with a
`programmingSkills`
property.

[source,java]
----
include::res/beans/Developer.java[]
----

The entries of
`programmingSkills`
should be shown in the
`Text`
widget as text separated by comma. Therefore a conversion is necessary.

In order to apply these converters an
`UpdateValueStrategy`
for the
binding needs to be defined and applied.

[source,java]
----
include::res/snippets/Converter.java[]
----

=== Validator
(((JFace Data Binding,Validator)))

A _validator_
allows you to implement validation of the data before it is propagated
to
the other connected property. A class which
wants to provide this
functionality must
implement the
`org.eclipse.core.databinding.validation.IValidator`
interface.

[source,java]
----
include::res/snippets/validator.java[]
----

TIP: The `WizardPageSupport` class provides support to connect the result from the given data
binding
context to the given wizard page, updating
the wizard page's
completion state and its error message accordingly.

