== Eclipse plug-ins and applications

=== Eclipse software components - Plug-ins
An Eclipse application consists of several Eclipse components.
A software component in Eclipse is called a _plug-in_.
The Eclipse platform allows the developer to extend Eclipse applications like the Eclipse IDE with additional functionalities via plug-ins.

Eclipse applications use a runtime based on a specification called _OSGi_.
A software component in OSGi is called a _bundle_.
An OSGi bundle is also always an Eclipse plug-in.
Both terms can be used interchangeably.

For example, a new plug-in can create new menu entries or toolbar entries.

=== Advantages of developing Eclipse plug-ins

The Eclipse platform forms the basis of the most successful Java IDE and therefore is very stable and broadly used. It uses native user interface components which are fast and reliable.
It has a strong modular approach based on the industry standard module system for Java (OSGi) that allows developers to design component based systems.

Companies such as IBM, SAP and Google use the Eclipse framework as a basis for their products and therefore need to ensure that Eclipse is flexible, fast and continues to evolve.

The Eclipse platform also fosters a large community of individuals which provide support, documentation and extensions to the Eclipse framework.
Tapping into this ecosystem allows you to find required resources and information.

=== What is the Eclipse Rich Client Platform (Eclipse RCP)?

The Eclipse IDE version 2.0 started as a modular IDE application.
In 2004 Eclipse version 3.0 was released. 
Eclipse 3.0 supported reusing components of the Eclipse platform to build stand-alone applications based on the same technology as the Eclipse IDE.

At this point, the term _Eclipse RCP_ was coined.
Eclipse RCP is short for _Eclipse Rich Client Platform_ and indicates that the Eclipse platform is used as a basis to create feature-rich stand-alone applications.

The release of Eclipse in version 4.x simplified and unified the Eclipse programming model which is now based on state-of-the-art technologies, like dependency injection and declarative styling via CSS files.

Eclipse RCP applications benefit from the existing user interface and the internal framework, and can reuse existing plug-ins and features.

