== Eclipse software components - Plug-ins

An Eclipse application consists of several Eclipse components.
A software component in Eclipse is called a _plug-in_.
The Eclipse platform allows the developer to extend Eclipse applications like the Eclipse IDE with additional functionalities via plug-ins.

Eclipse applications use a runtime based on a specification called _OSGi_.
A software component in OSGi is called a _bundle_.
An OSGi bundle is also always an Eclipse plug-in.
Both terms can be used interchangeably.

For example, a new plug-in can create new menu entries or toolbar entries.

== Extending the Eclipse IDE

The Eclipse IDE is basically an Eclipse RCP application to support development activities.
Even core functionality of the Eclipse IDE is provided via a plug-in, for example the Java development or the C development tools are contributed as a set of plug-ins.
Only if these plug-ins are present the Java or C development capabilities are available.

The Eclipse IDE functionality is heavily based on the concept of extensions and extension points.
For example the Java Development Tools provide an extension point to register new code templates for the Java editor.

Via additional plug-ins you can contribute to an existing functionality, for example new menu entries, new toolbar entries or provide completely new functionality.
But you can also create completely new programming environments.


