== Modularity support in Eclipse RCP
(((Application model,Modularity)))

Eclipse RCP applications are based on OSGi and therefore support
the modularity concept of OSGi. To contribute to the application
model, the Eclipse platform implements support for static and dynamic
contributions.

The initial structure of an RCP application is described via the
application
model in the
_Application.e4xmi_
file.

Other
plug-ins can extend this base application model with
contributions.
Model contributions can be statically defined in files.
These extensions are called
fragments
or
_model fragments_. Model contributions can also extend the model dynamically via code.
These extensions are called
_processors_
or
_model processors_.

These model contributions are registered with the Eclipse framework
via an extension point. To register your contributions you provide
extensions to the
`org.eclipse.e4.workbench.model`
extension point.

This extension point is defined in the
`org.eclipse.e4.ui.workbench`
plug-in.

The model contributions are read during startup and the
contained
information
is used
to build the runtime application model.

