== Eclipse and declarative styling

(((CSS, Eclipse)))
(((Eclipse styling, CSS)))
(((CSS,Styling of Eclipse applications))))
(((applicationCSS)))
The visual appearance of your Eclipse application can be styled via external files similar to the CSS 2.1 standard.
CSS selectors used in Eclipse are identifiers, which relate to widgets or other elements, for example predefined pseudo classes. 
Non-standard properties are prefixed with either `swt-` or `eclipse-`.
		
The following example shows a CSS file which defines a styling for an Eclipse application.

[source,css]
----
include::res/css/default.css[]
----
		

SWT has certain limitations concerning component styling. 
These limitations are based on the restrictions of the underlying operating system or limitation in SWT itself. 
For example, it is not possible to style menus and table headers because this is not supported by SWT. 
In addition some platforms do not allow the styling of certain widgets.
For example, the SWT implementation for Windows does not allow to set the background color of the  `Button` and the `ScrollBar` widget.

[NOTE]
====
In most cases it is possible to overcome the styling restrictions of SWT in RCP applications.
For example, you can use `NatTable` to display your tables.
NatTable is a flexible table and tree implementation which allows full styling.
For other components you can use custom widgets or use a `PaintListener` to draw on top of the widget.
====
