== Styling using themes
(((Theme service, CSS)))
(((CSS,Theming of Eclipse applications)))
(((IThemeEngine,CSS)))
(((cssTheme)))
	
You can define multiples _themes_ via an extension in the _plugin.xml_ file.
The Eclipse platform provides the theme service with an instance of the `IThemeEngine` interface. 
Via this instance you can change the active theme at runtime.
	
To create new themes you define extensions for the `org.eclipse.e4.ui.css.swt.theme` extension point. 
Such an extension defines an ID for the style and a pointer to the CSS file.
	
	
You must also define the default theme via the `cssTheme` property in your `org.eclipse.core.runtime.products` extension. 
This can also be used to define a fixed styling.

WARNING: You need to set `cssTheme` otherwise the theming services is available at runtime.
	
The switching of themes is demonstrated in the following handler code.
	
	
<programlisting>
	<xi:include xmlns:xi="http://www.w3.org/2001/XInclude"
parse="text" href="../examples/css/ThemeSwitchHandler.java" />
</programlisting>
	


