== Custom annotations

=== Custom annotations in Eclipse
(((Annotations,Custom annotations processors)))
The Eclipse platform uses dependency injection as the primary programming model. 
This mechanism is extensible with custom annotations.
The following code demonstrates how you can define your custom annotation.
		
[source,java]
----
include::res/DirectTodo.java[]
----

=== Define an annotation processor via an OSGi service
		
To process these custom annotations you can register an
OSGi
service for
the abstract
`ExtendedObjectSupplier`
class from the
`org.eclipse.e4.core.di.suppliers`
package. In this registration you define via
the
_dependency.injection.annotation_
property the annotation for which the service is
responsible.
		
After this registration the
Eclipse framework
calls
this
annotation
processor if it encounters
the configured annotation.
		
The following snippet shows an example
_DirectTodoSupplier.xml_
file which registers an
`ExtendedObjectSupplier`
for the
`DirectTodo`
annotation.
		
[source,java]
----
include::res/DirectTodoSupplier.xml[]
----

The annotation processor registered via the
_DirectTodoSupplier.xml_
file returns an object. The
following
code
shows an example for an
annotation processor which
returns an instance
of an
`java.util.Optional<Todo>`
class, in case a proper id is passed to the
`DirectTodo`
annotation.
		
[source,java]
----
include::res/DirectTodoObjectSupplier.java[]
----

=== Restrictions
    
Dependency injection can be used inside an ExtendedObjectSupplier implementation, so that services like the IEventBroker, EModelService and so on can be injected.
But _Extended object suppliers_ do not have access to the `IEclipseContext` in which they are called. 
This limits them to search for objects independent of the current Eclipse context. 
    
For example preferences are implemented as _extended object suppliers_.
They look for the preference values on the file system and do not know about the `IEclipseContext`.
    

		

