== Using model add-ons

=== What are model add-ons?
		
The application model allows you to create
model objects called
_add-ons_
. These components
can
enhance
the
application with
additional functionality.
		
Add-ons
add flexibility to the application model. They
allow you
to
extend or change the default Eclipse behavior
without
having to
modify
existing Eclipse code. You just have to replace the
related
model
component.
		
For example, the default
drag and drop support
of parts
in Eclipse
is implemented via an
add-on. Other examples are
the keybinding or the
command processing. If this functionality is undesired, you can
simply remove the component from
the application model. If you want a
different behavior, you simply register your own add-on in your
application model.
		
Add-ons
point to Java classes via their
_Class URI_
attribute using the
`bundleclass://`
URI convention.

=== Add-ons from the Eclipse framework
		
Currently the following standard
add-ons
are useful for Eclipse
applications. Their class names give an
indication
of
their
provided
functionality.
		
* `CommandServiceAddon`
* `ContextServiceAddon`
* `BindingServiceAddon`
* `HandlerProcessingAddon`
* `CommandProcessingAddon`
* `ContextProcessingAddon`
* `BindingProcessingAddon`

=== Additional SWT add-ons
		
Additional
add-ons
are available.
To support drag and drop for
parts
you need to add the
`org.eclipse.e4.ui.workbench.addons.swt`
plug-in to your product configuration file. Then you can use the
`DnDAddon`
and the
`CleanupAddon`
classes
from this bundle as
add-ons
in your application model. This
plug-in
contains also the
`MinMaxAddon`
class which allows adding the functionality to minimize or maximize your
application.
		
The
`org.eclipse.e4.ui.workbench.addons.swt`
plug-in contributes these add-ons automatically to your application
model via a model
processor at runtime.

=== Relationship to other services
		
Add-ons
are created before
the
Eclipse rendering framework
renders
the model and after
the
event
service has been
created.
		
This allows
add-ons
to alter the user interface that is produced by the
rendering
engine.

For example, the
`MinMaxAddon`
add-on
changes the tab folders
created for the part stacks
to have the min/max buttons in the corner.

The Eclipse platform uses events sent via the
event
service to
communicate changes in the application model.
For
example, if
a
part
is
activated, the Eclipse platform sends out an
event
for this.
Add-ons
can
subscribe to these events from
the Eclipse
platform
and react
to
them.
	
